import { Inter } from "next/font/google";
import "../style/global.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fashion-web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
